### ISSUE TITLE
bug: A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by KibaNoOu** [webcatalog/webcatalog-legacy#1468]
Hi, after the latest update of the main app and websites, this error keeps popping out when i try to launch any of the websites.

![immagine](https://user-images.githubusercontent.com/11923117/125627753-3835a997-9e9a-45d6-bd5f-1b08e7108b60.png)

**Comment by quanglam2807** [comment]
Thank you so much for reporting. We're rolling the fix.

Fixed with https://github.com/webcatalog/neutron/pull/525

**Comment by quanglam2807** [comment]
It's out. We're really sorry for this serious bug.

**Comment by KibaNoOu** [comment]
Your welcome!
Great support BTW!
But when i close the Web Catalog App i still get a Javascript Error, is this related?

![immagine](https://user-images.githubusercontent.com/11923117/125634925-cc1ecceb-d1c8-416e-87b9-0f2bec4669e8.png)
